### ISSUE TITLE
Looking for the guy who made 'Force Empty Trash' & 'Restart App' workflows for Alfred.

### ISSUE THREAD

**Issue by itsbrex** [renegaed/userscripts#1]
Is that you? No links or info on the Packal workflow pages so I figured I'd reach out here. If this is not you, please disregard. Otherwise, I had a question about the Restart App workflow - wondering why the workflow no longer displays the icons for each app in the list of running apps. 

Thanks in advance!

![2016-02-19 at 5 41 pm](https://cloud.githubusercontent.com/assets/9772694/13193593/06581b24-d730-11e5-9c01-e297ae6423a4.jpg)

**Comment by renegaed** [comment]
hey man yer that's me. Hmm that's interesting it works fine for me. I just deleted it and downloaded it again and no issue. What OSX version are you using? When have you noticed this?

**Comment by renegaed** [comment]
Hey man, yep it's me. So that I can see what's happening in your case follow these instructions:
1. Open up the restart workflow in Alfred
2. Turn on debugging mode (click the bug icon on the top right)
3. Change the "Log" dropdown menu to "All Information"
4. Use "Restart" workflow through Alfred once. It will populate the log area
5. Copy and paste that info here.

<img width="1212" alt="alred_restart_debug_info" src="https://cloud.githubusercontent.com/assets/1324711/13250665/65b9d646-da7f-11e5-879b-9f1b175b3236.png">

**Comment by renegaed** [comment]
Also do this. Download this file.
[test.rb.zip](https://github.com/renegaed/userscripts/files/142450/test.rb.zip)
Put it inside your Downloads directory and unzip it.
Open Terminal.app (located /Applications/Utilities/Terminal.app)
Copy and paste the following into Terminal and click enter
`cd ~/Downloads && ruby test.rb`
It should output some text that looks like this.
<img width="832" alt="terminal_test" src="https://cloud.githubusercontent.com/assets/1324711/13251104/44e56b9e-da82-11e5-9900-0fea42dafb67.png">

Copy and paste that here. Following the instructions from the above comment and this one should be plenty for me to see what's going on. Cheers.

**Comment by itsbrex** [comment]
Here's the debug output: 

`[INFO: alfred.workflow.input.scriptfilter] <items>
  <item uid="status" arg="Alfred Preferences">
    <title>Alfred Preferences</title>
    <subtitle>Press Enter to activate alias Stuff/Applications/Alfred 2.app/Contents/Preferences/Alfred Preferences.app</subtitle>
    <icon type="fileicon">alias Stuff/Applications/Alfred 2.app/Contents/Preferences/Alfred Preferences.app</icon>
  </item>
  <item uid="status" arg="MIDIPlayer X">
    <title>MIDIPlayer X</title>
    <subtitle>Press Enter to activate alias Stuff/Applications/MIDIPlayer X.app</subtitle>
    <icon type="fileicon">alias Stuff/Applications/MIDIPlayer X.app</icon>
  </item>
  <item uid="status" arg="Safari">
    <title>Safari</title>
    <subtitle>Press Enter to activate alias Stuff/Applications/Safari.app</subtitle>
    <icon type="fileicon">alias Stuff/Applications/Safari.app</icon>
  </item>
  <item uid="status" arg="Scale Suggestor">
    <title>Scale Suggestor</title>
    <subtitle>Press Enter to activate alias Stuff/Applications/Scale Suggestor.app</subtitle>
    <icon type="fileicon">alias Stuff/Applications/Scale Suggestor.app</icon>
  </item>
  <item uid="status" arg="TextEdit">
    <title>TextEdit</title>
    <subtitle>Press Enter to activate alias Stuff/Applications/TextEdit.app</subtitle>
    <icon type="fileicon">alias Stuff/Applications/TextEdit.app</icon>
  </item>
  <item uid="status" arg="iTunes">
    <title>iTunes</title>
    <subtitle>Press Enter to activate alias Stuff/Applications/iTunes.app</subtitle>
    <icon type="fileicon">alias Stuff/Applications/iTunes.app</icon>
  </item>
  <item uid="status" arg="Finder">
    <title>Finder</title>
    <subtitle>Press Enter to activate alias Stuff/System/Library/CoreServices/Finder.app</subtitle>
    <icon type="fileicon">alias Stuff/System/Library/CoreServices/Finder.app</icon>
  </item>
  <item uid="status" arg="Music Folder Files Not Added">
    <title>Music Folder Files Not Added</title>
    <subtitle>Press Enter to activate alias Stuff/Users/anodigital/Library/iTunes/Scripts/Music Folder Files Not Added.app</subtitle>
    <icon type="fileicon">alias Stuff/Users/anodigital/Library/iTunes/Scripts/Music Folder Files Not Added.app</icon>
  </item>
</items>`

**Comment by itsbrex** [comment]
Here is the terminal output:

![2016-02-29 at 11 48 am](https://cloud.githubusercontent.com/assets/9772694/13406793/4afa7cac-deda-11e5-8ce7-7b5578b9058a.jpg)

**Comment by renegaed** [comment]
Hey I have rewritten the workflow from the ground up.
You can access the latest 2.1 version on Packal.org
Try it out and let me know here whether it is working or not. I have also updated the workflow to restart applications in an intelligent manner. This means that you should notice it restarting apps much faster now. Cheers.

**Comment by itsbrex** [comment]
Works perfectly! You da man. 
![l6jm0_fi-200x200](https://cloud.githubusercontent.com/assets/9772694/13478835/d6de78dc-e087-11e5-810a-a76408616f47.gif)

**Comment by itsbrex** [comment]
Does this work when you try to restart Spotify?

**Comment by renegaed** [comment]
Hey man nice catch! I have done another major update to the workflow to both fix this issue and also incorporate some nifty features that I recently added for myself. Here is the info below:
1. Fixed Spotify restart issue.
2. The app will now show a much wider range of applications than it used to
3. Introduction of the Exclude List

**Exclude List**
Because the workflow will now show many more processes than it used to, I have given the user the ability to optionally hide processes from appearing in the list eg. Evernote Helper, Spotify Helper.
In order to do this hover over the process name and press CMD+ENTER. This will add the process to the Exclude List.

You can view/edit the Exclude List manually using the keyword "rexclude"

---

As before you can download the latest (3.1 version) on Packal.org. Let me know how it's working for you and whether or not you can restart Spotify successfully now. Cheers.

**Comment by itsbrex** [comment]
@renegaed again, works like a charm! I wonder if could be a way to bulk processes to the Exclude List because it could take a while to build :/ 

If not, no worries. I can just go thru one-by-one. Suppose it wouldn't actually take that long.

![gume39nvdd](https://cloud.githubusercontent.com/assets/9772694/13732913/ba40e5ba-e948-11e5-9e5f-afdc400c9a63.gif)

**Comment by renegaed** [comment]
Good to see it's working well! You should only be excluding processes that are not really standalone apps but part of other apps. Also if you type "restart {keyword}" you can obviously shorten the list to the app you are looking for eg. "restart spo" for spotify. But going through one-by-one is the best option due to Alfred's current limitations. It's a one-off thing and IMO a small trade-off for the huge amount of choices you now have. Bask in the glory!

**Comment by itsbrex** [comment]
@renegaed ha ha, right on. thanks man. appreciate it!

**Comment by renegaed** [comment]
no worries : )
